### PR TITLE
Add proto3 optionals support

### PR DESCRIPTION
**Pull request by Adphi**

### CODE REVIEW

**Comment by Adphi** [comment]
@yuval-k, any chances to have this PR moving on?

**Comment by conradhanson** [comment]
Hi @Adphi, thanks for your contribution! 

We decided to open a [separate PR](https://github.com/solo-io/protoc-gen-ext/pull/20) on an internal branch that includes your changes so we can test against several of our private repos to verify these changes don't break anything.

As it stands, we are awaiting reviews/approvals on the pr noted above.

**Comment by conradhanson** [comment]
Closing this PR as the one linked above (that includes these changes) has been merged.

**Pull request closed without merging**
